services:
  - type: web
    name: mines-game-payments
    env: node
    plan: free
    buildCommand: "npm ci"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
